services:
  api-gateway:
    build:
      context: .
      dockerfile: docker/api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      - AUTH_API_URL_DEV=${AUTH_API_URL_DEV}
      - USER_API_URL_DEV=${USER_API_URL_DEV}
      - TIMER_API_URL_DEV=${TIMER_API_URL_DEV}
    volumes:
      - ./src/api-gateway:/usr/src/api-gateway 
    ports:
    - "3000:3000"

  user:
    build:
      context: .
      dockerfile: docker/user-service/Dockerfile
    container_name: user
    environment:
      - MONGODB_URI=${MONGODB_USER_DB_URI}
      - PORT=${PORT_USER}
      - JWT_KEY=${JWT_KEY}
      - AUTH_API_URL_DEV=${AUTH_API_URL_DEV}
      - TIMER_API_URL_DEV=${TIMER_API_URL_DEV}
    volumes:
      - ./src/user-service:/usr/src/user-service 
    depends_on:
      - user-db
    ports:
    - "3100:3100"


  auth:
    build:
      context: .
      dockerfile: docker/auth-service/Dockerfile
    container_name: auth
    environment:
      - PORT=${PORT_AUTH}
      - JWT_KEY=${JWT_KEY}
      - USER_API_URL_DEV=${USER_API_URL_DEV}
      - TIMER_API_URL_DEV=${TIMER_API_URL_DEV}
    volumes:
      - ./src/auth-service:/usr/src/auth-service 
    ports:
    - "3300:3300"

  timer:
    build:
      context: .
      dockerfile: docker/timer-service/Dockerfile
    container_name: timer
    environment:
      - MONGODB_URI=${MONGODB_TIMER_DB_URI}
      - PORT=${PORT_TIMER}
      - USER_API_URL_DEV=${USER_API_URL_DEV}
      - AUTH_API_URL_DEV=${AUTH_API_URL_DEV}

    volumes:
      - ./src/timer-service:/usr/src/timer-service  
    depends_on:
      - timer-db
    ports:
    - "3200:3200"


  user-db:
    build:
      context: .
      dockerfile: docker/mongodb/Dockerfile    
    container_name: user-db
    environment:
      - MONGO_INITDB_DATABASE=${USER_DB}
    ports:
      - "27017:27017"

  timer-db:
    build:
        context: .
        dockerfile: docker/mongodb/Dockerfile   
    container_name: timer-db
    environment:
      - MONGO_INITDB_DATABASE=${TIMER_DB}
    ports:
      - "27018:27018"