services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: docker/node/Dockerfile
  #   container_name: node
  #   environment:
  #     - MONGODB_URI=${MONGODB_URI}
  #     - JWT_KEY=${JWT_KEY}
  #   volumes:
  #     - ./src/api:/usr/src/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo

  api-gateway:
    build:
      context: .
      dockerfile: docker/api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      - name=value
    volumes:
      - ./src/api-gateway/:usr/src/api-gateway

  user:
    build:
      context: .
      dockerfile: docker/user-service/Dockerfile
    container_name: user
    environment:
      - MONGODB_USER_DB_URI=${MONGODB_USER_DB_URI}
      - PORT=${PORT_USER}
    volumes:
      - ./src/user-service:/usr/src/user-service
    depends_on:
      - user-db

  auth:
    build:
      context: .
      dockerfile: docker/auth-service/Dockerfile
    container_name: auth
    environment:
      - name=value
    volumes:
      - ./src/auth-service:/usr/src/auth-service

  timer:
    build:
      context: .
      dockerfile: docker/timer-service/Dockerfile
    container_name: timer
    environment:
      - name=value
    volumes:
      - ./src/timer-service:/usr/timer-service
    depends_on:
      - timer-db

  # mongo:
  #   image: mongo:4.4
  #   container_name: mongo
  #   environment:
  #     - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  user-db:
    image: mongo:4.4
    container_name: user-db
    environment:
      - MONGO_INITDB_DATABASE=${USER_DB}
    ports:
      - "27017:27017"

  timer-db:
    image: mongo:4.4
    container_name: timer-db
    environment:
      - MONGO_INITDB_DATABASE=${TIMER_DB}
    ports:
      - "27018:27018"
