services:
  api:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: node
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_KEY=${JWT_KEY}
    volumes:
      - ./src/api:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      # - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    # volumes:
    # - mongodb_data:/data/db
    # - ./mongodb/mongod.conf:/etc/mongod.conf
    # - ./mongodb/mongod/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    ports:
      - "27017:27017"
#   mongo-express:
#     image: mongo-express:1.0.2-20-alpine3.19
#     container_name: mongo-express
#     environment:
#       - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
#       - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
#       - ME_CONFIG_MONGODB_URL=${MONGODB_URI}
#     ports:
#       - "${MONGO_EXPRESS_PORT}:8081"
#     depends_on:
#       - mongo

# volumes:
#   mongodb_data:
